Vagrant.configure("2") do |config|
  config.vm.box = "fedora/32-cloud-base"
  config.vm.box_version = "32.20200422.0"
  # $ vagrant plugin install vagrant-disksize
  config.disksize.size = '64GB'
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  
  config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 4
  end

  config.vm.synced_folder "./repos/", "/tmp/repos/"
  config.vm.provision "shell",
    inline: "cp -f /tmp/repos/* /etc/yum.repos.d/"

  config.vm.provision "shell", path: "init.sh"
end
