Vagrant.configure("2") do |config|
  config.vm.box = "fedora/32-cloud-base"
  config.vm.box_version = "32.20200422.0"
  config.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus = 2
  end

  config.vm.synced_folder "./repos/", "/tmp/repos/"
  config.vm.provision "shell",
    inline: "cp -f /tmp/repos/* /etc/yum.repos.d/"

  config.vm.provision "shell", path: "init.sh"
end
